Add support for Enchantment Descriptions.
Ladysnake/Requiem pull request #641
Opened 2023-10-04 06:45 UTC by Darkhax

This PR adds support for my [Enchantment Descriptions](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions) mod and other mods with similar features.

2023-10-04 07:35 UTC, Pyrofab requested changes
Thank you ! Just a little typo if I am not mistaken.

2023-10-04 07:35 UTC, Pyrofab commented on src/main/resources/assets/requiem/lang/en_us.json
> +  "enchantment.requiem.humanity.desc": "Improves drops obtained by posessed mobs.",
```suggestion
  "enchantment.requiem.humanity.desc": "Improves drops obtained by possessed mobs.",
```

2023-10-04 07:36 UTC, Darkhax commented
Yep you're right, nice catch.

2023-10-04 07:37 UTC, UpcraftLP approved these changes

2023-10-23 17:08 UTC, Darkhax commented
Hey, are there any updates on getting this merged?

2023-10-23 17:39 UTC, Pyrofab commented
Oh yeah, thanks for reminding me

2023-10-23 17:39 UTC, Pyrofab approved these changes

2023-10-23 19:11 UTC, Darkhax commented
Awesome, thank you!

2023-10-23 21:25 UTC, merged